name: Joke Gemini Bot - Daily Update + Snake

on:
  schedule:
    - cron: "0 12 * * *" # daily at 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Generate joke & news
        id: gemini
        run: |
          OUTPUT="$(node main.js)"
          echo "output=$OUTPUT" >> "$GITHUB_OUTPUT"
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Generate GitHub snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark

      - name: Commit changes
        run: |
          git config user.name "gemini-bot"
          git config user.email "gemini-bot@users.noreply.github.com"

          git add jokes.txt news.txt joke.svg news.svg dist/

          git commit -m "$(date +%Y-%m-%d) - Repo updated against my will: ${{ steps.gemini.outputs.output }}" || echo "No changes"
          git push

